const mongoose = require('mongoose');

/**
 * EmbedToken — Short-lived, single-use token for iframe authentication.
 * ─────────────────────────────────────────────────────────────────────────────
 * Generated by the Partner API (POST /accounts/:id/embed-token) and consumed
 * by the embed page (GET /api/embed/auth?token=emb_xxx) to exchange for a
 * real JWT session.
 *
 * Security properties:
 *   - Expires in 5 minutes (MongoDB TTL index auto-deletes)
 *   - Single-use (usedAt is set on first exchange, subsequent attempts fail)
 *   - Scoped to a specific tenant account + partner
 */
const embedTokenSchema = new mongoose.Schema({
    // Format: emb_<48 hex chars>
    token: {
        type: String,
        required: true,
        unique: true,
        index: true
    },

    // The provisioned account this token authenticates as
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },

    // Which partner generated this token
    partnerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'PartnerApp',
        required: true
    },

    // Single-use enforcement: null until consumed
    usedAt: {
        type: Date,
        default: null
    },

    createdAt: {
        type: Date,
        default: Date.now
    }
});

// TTL index: auto-delete tokens 5 minutes after creation.
// Even if never used, they vanish from the DB automatically.
embedTokenSchema.index({ createdAt: 1 }, { expireAfterSeconds: 300 });

module.exports = mongoose.model('EmbedToken', embedTokenSchema);
